### ISSUE TITLE
Blog Post Block Doesn't Show All Posts

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/newspack-blocks#438] opened 2020-04-23 23:03 UTC
If I have seven posts and set the Number of Items to two and choose the "More" Button option I see two posts then "Load more Posts" then I see two more then I do that a third time and see two more then again and I see the seventh post. That is good.

If I change the Number of items to two or more and choose the "More" Button option, then I see three load and see the "Load More Posts" option. I see the next three but there is no option to see the final post. No more "Load More Posts" choices.

Expected behavior
I would expect a Load More Posts option until all the posts are shown.

Editor version (please complete the following information):

    WordPress version: [e.g: 5.3.2] 5.4
    Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Default WordPress.com
    If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

Desktop (please complete the following information):

    OS: [e.g. iOS] MacBook Pro using Catalina

This came in as a live chat issue, and I replicated it on my test site.

**Comment by tijosh** [comment] 2020-05-26 18:48
+1 

#21413911-hc

**Comment by chaitanyamsv** [comment] 2020-06-25 00:57
+1 

#22108411-hc

**Comment by dcoleonline** [comment] 2020-06-30 20:10
+1

#3096323-zen

**Comment by susanjanec** [comment] 2020-08-12 13:19
+1 

#3209134-zen

**Comment by marutim** [comment] 2020-08-18 11:16
+1

23441801-hc

**Comment by csnlima** [comment] 2020-08-28 13:38
+1

#3250403-Zen

**Comment by gwensmithx** [comment] 2020-09-04 02:21
I'm not sure if this is related or not, but I've been able to reproduce a bug on a Simple Site where if you have more than 1 Blog Posts Block on a page, the Load More Posts button will only show up on the first Blog Posts block. And actually on the 3rd block I added it just said "sorry no posts were found".

Site is simple site and same issue on multiple themes so the theme doesn't seem to be the issue.

Let me know if you want me to open a new issue for this. To reproduce just add multiple blog posts block on a page with the More Posts button enabled.

3273928-zen

**Comment by tanjoymor** [comment] 2020-09-05 22:40
@marekhrabe Is this report related: https://github.com/Automattic/newspack-blocks/issues/404 ?

**Comment by RafaelFunchal** [comment] 2020-09-10 12:54
+1 3303521-zen

**Comment by sophiegyo** [comment] 2020-09-24 14:46
I had another instance of this here: 23955015-hc

It seems like the Load More button works three times, then after the third it just doesn't show. 

I've been trying to test on one of my sites too, but unfortunately my Blog Posts block doesn't even have the "show load more" button, so I've been unable to replicate it so far.

**Comment by dcoleonline** [comment] 2020-10-08 13:00
20877947-hc
 Blog Posts block was set to show 4 posts. The Load More button only appeared once. They had a total of 10 published posts, so 2 of them could not be seen. I suggested using the Recent Posts block for now.

**Comment by supernovia** [comment] 2020-10-24 22:30
I found another case here:
https://wordpress.com/forums/topic/cant-see-my-older-post/#post-3583034

If we change the block to show as many posts as exists, it works, otherwise the last couple of posts are gone.

**Comment by eduardozulian** [comment] 2020-10-27 14:38
Another case with a Newspack user at 3438873-zen

**Comment by sophiegyo** [comment] 2020-11-15 12:09
I think we have another case of this here: 3490047-zen

That's aside from the fact that I can no longer even find the more button toggle in the block settings?

**Comment by sandymcfadden** [comment] 2020-12-19 12:59
Had another example of this here 25657292-hc

**Comment by supernovia** [comment] 2021-01-14 20:53
https://wordpress.com/forums/topic/blog-posts-block-not-showing-all-posts-even-with-less-than-100-posts/

**Comment by supernovia** [comment] 2021-01-14 20:53
https://wordpress.com/forums/topic/all-the-posts-are-not-showing-up-2/

**Comment by supernovia** [comment] 2021-01-14 20:55
Oh, see also: https://github.com/Automattic/newspack-blocks/issues/404

**Comment by sophiegyo** [comment] 2021-02-02 08:53
Another case here: 3702319-zen

**Comment by adekbadek** [comment] 2021-04-02 15:32
Looks like a duplicate of #404, and so fixed on Feb 4. I've followed the steps from the top comment, but cannot reproduce.

**Closed by adekbadek** 2021-04-02 15:32 UTC
Labels: Involves Happiness, [Block] Homepage Posts, bug
