### ISSUE TITLE
Post Carousel Block (WP.com): Allow for alignment options

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/newspack-blocks#502] opened 2020-06-01 12:44 UTC
**Is your feature request related to a problem? Please describe.**
We should allow users to set the block to different alignment types: Wide, Full Width, to make the block options better and more in line with other blocks we have in the platform.

**Describe the solution you'd like**
Allow for alignment options selection on the block top toolbar.

**Comment by laurelfulford** [comment] 2020-06-02 18:41
Thanks for reporting this, @davipontesblog!

It looks like a duplicate of #488, so I'm going to close this specific issue; if if you think anything is missing from that issue, please add a comment. Thanks!

**Closed by laurelfulford** 2020-06-02 18:41 UTC
Labels: [Block] Carousel
