### ISSUE TITLE
Add new exclusion under Homepage Posts' "advanced filters."

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-blocks#720] opened 2021-03-23 16:05 UTC
The Post Inserter for the Newsletter offers a bit more control than the Hompage Posts block. By adding Exclude Tags to the advanced filters, this would bring them into parity and give publishers more control over the Homepage Blocks. 

And maybe on the Post Inserter, it makes sense to bring the Tags field out from under the filters, just leaving the two exclusion fields under the "advanced filters."

Either way, these two blocks essentially do the same thing, so I figured they should look the same.

Current Homepage Posts controls, with advanced filters expanded
![Screen Shot 2021-03-23 at 11 01 56 AM](https://user-images.githubusercontent.com/48489469/112178103-83262500-8bc7-11eb-99d5-fa49b909d9e6.png)

Current Post Inserter, with advanced filters expanded
![Screen Shot 2021-03-23 at 11 02 40 AM](https://user-images.githubusercontent.com/48489469/112178289-a355e400-8bc7-11eb-8e00-18180d92f95e.png)

**Comment by gamebits** [comment] 2021-09-02 22:13
Duplicate of https://github.com/Automattic/newspack-blocks/issues/600; resolved in https://github.com/Automattic/newspack-blocks/pull/821.

If there's some unique functionality I'm overlooking, please let me know, and we can reopen!

**Closed** 2021-09-02 22:13 UTC
