### ISSUE TITLE
Blog Posts Block: On un-Launched sites Load More Posts button doesn't work

### ISSUE THREAD

**Issue by jacoswan** [Automattic/newspack-blocks#397] opened 2020-02-28 08:03 UTC
#### Steps to reproduce

Only an issue on newly created, un-Launched sites "Launching" the site solves the issue.

1. Start on an Un-launched site, 1 page, 5 posts (tested on Premium)
2. One page, add a Blog Posts block, set to show 3 posts
3. Publish, and visit the page, click the "Load most posts" button. Nothing happens. 

#### What I expected
I expected the remaining posts to load. 

#### What happened instead
The button disappears, it says "Loading..." for a few seconds, then the button returns with a message:
`Something went wrong. Please refresh the page and/or try again`
Refreshing doesn't help. 

![something-went-wrong](https://user-images.githubusercontent.com/15178758/75521248-ff275b00-5a0f-11ea-9e66-d2c4cf490486.jpg)

#### Browser / OS version

Chrome 80.0.3987.106
Firefox 72.0.2
Mac OS Catalina 10.15.2

User's theme: Redhill
Also tested on: Twenty Twenty (can recreate on un-Launched site)

#### Screenshot / Video

Premium plan, theme Redhill:

![Screen Capture on 2020-02-28 at 09-57-18](https://user-images.githubusercontent.com/15178758/75521617-c9cf3d00-5a10-11ea-8678-d10a8bd086c4.gif)

From Console:

![image](https://user-images.githubusercontent.com/15178758/75521696-f1260a00-5a10-11ea-81e8-d2db67884443.png)

#### Context / Source

#user-report #2750354-zen

**Comment by katinthehatsite** [comment] 2020-03-09 19:36
Wanted to add a comment that when the site is set to private, that "Show More Button" in the display settings is missing and it is not possible to add the button at all:

<img width="304" alt="Screen Shot 2020-03-09 at 3 36 19 PM" src="https://user-images.githubusercontent.com/25575134/76250468-ceb79c00-621b-11ea-963d-747f2956f559.png">

**Comment by tullyhansen** [comment] 2020-06-04 11:10
Possible dupe of https://github.com/Automattic/newspack-blocks/issues/306?

**Comment by donalirl** [comment] 2020-12-15 09:40
Encountered in #26350926-hc where a site set to private did not have the Show More button at all in the block settings. When setting to public, the option appears. 

Pinging @adekbadek and @WunderBart since you fixed similar issues in #507 and #306 respectively. Not sure if this is related to the new public-by-default?

**Comment by adekbadek** [comment] 2021-03-26 13:25
There should be a notice displayed, is there not?

![image](https://user-images.githubusercontent.com/7383192/112638024-161cc480-8e3f-11eb-8970-f636006acc06.png)

**Comment by adekbadek** [comment] 2021-04-02 14:54
Closing due to lack of response. The issue is resolved for now by displaying the notice 👆

**Closed by adekbadek** 2021-04-02 14:54 UTC
Labels: [Block] Homepage Posts, bug
