### ISSUE TITLE
Allow homepage blocks to opt-out of de-dupe logic

### ISSUE THREAD

**Issue by davisshaver** [Automattic/newspack-blocks#1423] opened 2023-04-10 13:11 UTC
**Is your feature request related to a problem? Please describe.**
As a homepage producer, I would like to include a "news ticker" module which contains a headline list of all recently published articles, even if those articles are being used in another area of the homepage.

**Describe the solution you'd like**
A toggle on the block such as "Allow duplicate stories" or something of that nature.

**Describe alternatives you've considered**
The "Choose specific posts" option does circumvent de-dupe logic, but doing that for every story published would be time-prohibitive.

**Additional context**
Here's an example from the Philadelphia Inquirer showing how the same story is included twice on the homepage. ("Pennsylvania ranked worst"...)

![Screenshot 2023-04-10 at 9 11 19 AM](https://user-images.githubusercontent.com/1636964/230907573-6f02f8a8-a6d8-4006-bc35-28572b42614a.png)

![Screenshot 2023-04-10 at 9 11 16 AM](https://user-images.githubusercontent.com/1636964/230907587-9908d579-f726-4ba5-aa20-173496dc9991.png)

**Comment by gamebits** [comment] 2023-10-02 16:39
Closing as duplicate of https://github.com/Automattic/newspack-blocks/issues/258.

**Closed by gamebits** 2023-10-02 16:39 UTC
