### ISSUE TITLE
Blog Posts Block - "load more" button doesn't format properly

### ISSUE THREAD

**Issue by openfist** [Automattic/newspack-blocks#357] opened 2020-02-01 01:17 UTC
#### Steps to reproduce the issue

1. add blog posts block
2. toggle "Show More" button and a button will show at the bottom of the posts listed
3. preview and actual sites do not show formatting

https://cloudup.com/c44EwbBaWYZ

#### What I expected

I expected a formatted button to show

#### What happened instead

The site will load a link with no formatting to the button

 more options to the button formatting

**Comment by laurelfulford** [comment] 2020-03-11 21:46
@openfirst what theme is that site using? 

By default, the block just uses the `button` tag and only adds a top margin as a style -- so however the theme is styling the button should be applied to the block. My best guess is this theme is styling the button this way, but that's a total shot in the dark!

**Comment by dkoo** [comment] 2021-07-12 18:09
Closing this—the "load more" button takes on button styles for the current theme, which is the intended behavior.

**Comment by pbking** [comment] 2022-06-10 15:04
Reopening this based on findings looking into https://github.com/Automattic/themes/issues/5739.

This block isn't leveraging a button block which is what picks up button styles. Block themes don't style the `<button>` element but rather use Global Styles to style Button Blocks.

**Comment by edwinho89** [comment] 2022-06-13 07:55
5291861-zd-woothemes - Provided CSS workaround from https://github.com/Automattic/themes/issues/5739

**Comment by happychait** [comment] 2022-07-04 00:42
Another one in 35973215-hc
Gave this custom CSS fix:

```
/* Temporary load more button CSS on blog post */
.wp-block-newspack-blocks-homepage-articles button {
    border-radius: 100px;
    background-color: #0893E3 !important;
    border-width: 0;
    color: #fff;
    font-size: var(--wp--custom--button--typography--font-size);
    padding-top: calc(var(--wp--custom--button--spacing--padding--top) + var(--wp--custom--button--border--width));
    padding-bottom: calc(var(--wp--custom--button--spacing--padding--bottom) + var(--wp--custom--button--border--width));
    padding-left: calc(var(--wp--custom--button--spacing--padding--left) + var(--wp--custom--button--border--width));
    padding-right: calc(var(--wp--custom--button--spacing--padding--right) + var(--wp--custom--button--border--width));
    text-decoration: none;
    font-weight: var(--wp--custom--button--typography--font-weight);
}

```

**Comment by csabarakasz** [comment] 2022-07-10 06:22
Another one:

- [ ] 36023327-hc

Used this code: 
```
/* Fix: Blog Posts Block: Load More Posts button doesn't have the same styling as seen in editor | XXXXXX-hc/zen GH */

.wp-block-newspack-blocks-homepage-articles button {
  border-width: 0;
  border-radius: 5px;
  color:white;
  font-size: 1.1em;
  background-color: #6F7B42;
  padding-top: calc(var(--wp--custom--button--spacing--padding--top) + var(--wp--custom--button--border--width));
  padding-bottom: calc(var(--wp--custom--button--spacing--padding--bottom) + var(--wp--custom--button--border--width));
  padding-left: calc(var(--wp--custom--button--spacing--padding--left) + var(--wp--custom--button--border--width));
  padding-right: calc(var(--wp--custom--button--spacing--padding--right) + var(--wp--custom--button--border--width));
  text-decoration: none;
  font-weight: var(--wp--custom--button--typography--font-weight);
}

.wp-block-newspack-blocks-homepage-articles button:hover {
  background-color: #6F7B42;
}

/* End  | XXXXXX-hc/zen */
```

**Comment by laurelfulford** [comment] 2022-09-01 16:43
This should be fixed with https://github.com/Automattic/newspack-blocks/pull/1252

The issue was that the button in the editor had the CSS class `.wp-block-button__link`, but it didn't have it on the front-end, so it would inherit the styles of the button block in the editor, and just display as a regular old button on the front-end. That PR added the same CSS class to the front-end. 

I'm going to close this issue as it's resolved in the repository, but it still needs to be synced to WP.com; the latest discussion on that is here: p1660763548381799-slack-newspack-support.

**Closed by laurelfulford** 2022-09-01 16:43 UTC
Labels: [Block] Homepage Posts, [Type] Bug
