### ISSUE TITLE
Blog Posts Block: Choose specific stories not working

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/newspack-blocks#309] opened 2019-12-22 19:21 UTC
**Describe the bug**
The "Choose specific stories" feature isn't working (it doesn't display any posts and you can't input post IDs).

**To Reproduce**
1. Add a new page
2. Add the Blog Posts block
3. Click the toggle switch for "Choose specific stories"
4. Enter post ID in the field and either click enter or add a comma
5. The ID number just disappears and no post displays
6. You also can't add more than one ID

Tested on themes: Twenty Sixteen, Twenty Twenty, Mayland, Penscratch 2

**Screenshots**
Recording of the process: https://d.pr/v/z82g4k

**Expected behavior**
I expected the ID number to stay in the field, to be able to add more than one ID, and for the block to display the posts per their IDs.

User report: #2579306-zen

**Comment by jeffersonrabb** [comment] 2019-12-22 19:32
The "Specific Stories" feature uses title autocompletion, not Post IDs. To use it, begin typing in the title of the post (or posts) you wish to display, and when the post title is shown, select it. Here's a video demonstrating the use: https://cloudup.com/iMZRYGx_hl7

**Comment by tanjoymor** [comment] 2019-12-22 19:35
Hmmmm, that doesn't feel apparent. So maybe not a "bug" - should this get changed to a feature request? Either to enable IDs to work or to offer a tool tip that explains that users?

**Comment by jeffersonrabb** [comment] 2019-12-22 19:39
Sure! I'll close this issue since the feature is working as intended, then would you open a feature request for the tooltip? Supporting post IDs doesn't feel like the right direction since users are much more likely to be familiar with post titles than IDs, but adding instructions sounds like a good idea.

**Closed by jeffersonrabb** 2019-12-22 19:39 UTC
Labels: bug
