### ISSUE TITLE
Homepage Posts: Use Top Posts instead of specific/filters

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#712] opened 2021-03-08 14:20 UTC
**Is your feature request related to a problem? Please describe.**
Many publishers want to show the most popular posts on their site. They can do so using Jetpack's Top Posts & Pages widget and associated shortcode but this provides very few options. The display of these posts is then also inconsistent with the rest of the posts on display.

**Describe the solution you'd like**
When configuring a homepage posts block users will have a "Top posts" option, similar to the "Display specific posts" option that would remove the available filters and instead piggyback on Jetpack's query for grabbing top posts.

**Describe alternatives you've considered**
Making a block in Jetpack that matches the options of the homepage posts block, but that might be unwanted duplication of the block options logic.

**Additional context**
Several publishers have asked for this feature.

**Comment by adekbadek** [comment] 2022-09-23 08:13
Duplicate of https://github.com/Automattic/newspack-blocks/issues/49

**Closed by adekbadek** 2022-09-23 08:13 UTC
Labels: enhancement, feature request
