### ISSUE TITLE
Blog Post Block Missing Sharing Icons

### ISSUE THREAD

**Issue by arcangelini** [Automattic/newspack-blocks#420] opened 2020-03-22 21:35 UTC
**Describe the bug**
When using the Blog Posts block with the sharing icons enabled in Jetpack the logos do not load on the posts. This appears to specifically happen when you *disable* sharing icons on **pages**, but enable them on **posts**.

**To Reproduce**
1. Enable Jetpack sharing buttons and set to "Icons Only" 
2. Adjust the setting to Allow on "Posts" only
3. Add a Blog Post block on any page

**Screenshots**
[![Screenshot](https://d.pr/i/Hl06Sn+)](https://d.pr/i/Hl06Sn)

**Expected behavior**
The sharing buttons should display logos inside the circle

[![Screenshot](https://d.pr/i/uxijGP+)](https://d.pr/i/uxijGP)

#2809894-zen

**Comment by ccwalburn** [comment] 2020-07-24 21:20
Another user report here: 3170967-zen

**Comment by liviopv** [comment] 2020-07-26 11:58
Another case #22911851-hc
Slack: https://a8c.slack.com/archives/C03TY6J1A/p1595763616100300

**Comment by donalirl** [comment] 2020-08-31 00:47
Another case in #3253775-zen

**Comment by donalirl** [comment] 2020-08-31 01:03
It seems that you specifically need to enable sharing buttons on Pages under Marketing → Sharing Buttons. Without that, the Blog Posts block will not show the sharing button icon on the *page*, but it will still show it on the individual *posts*.

**Comment by nagpai** [comment] 2020-09-17 02:31
Another issue #24191494-hc

@katiebethbrown  helped me with this. The sharing buttons appeared correctly after Marketing >> Sharing buttom settings were enabled correctly. If it is disabled then the buttons should not show at all instead of erroneous buttons, or the block settings should override the marketing settings.

**Comment by eduardozulian** [comment] 2020-10-30 20:34
Another similar report in 24960692-hc  However, in this case, we have an Elementor posts widget. I believe that the issue is actually with Jetpack: once the sharing is disabled for pages, it treats the sharing buttons inside post listings the same way:

<img width="1215" alt="Captura de Tela 2020-10-30 às 17 31 23" src="https://user-images.githubusercontent.com/1136160/97754161-c5927c80-1ad5-11eb-9469-79dc14b7406f.png">


cc @jeherve

**Comment by jeherve** [comment] 2020-11-02 10:47
> once the sharing is disabled for pages, it treats the sharing buttons inside post listings the same way

That is correct. It was built that way on purpose. 

In the past, we've recommended to folks that they remove the sharing markup from those areas if they don't intend to show sharing buttons, like it's done here for example:
https://github.com/Automattic/jetpack/blob/8b7e85a596d0b352bdb6c193df0e9427be2ab394/modules/theme-tools/compat/twentyfourteen.php#L42-L57

**Comment by eduardozulian** [comment] 2020-11-17 19:13
This is also happening on 25670395-hc 

For now, I'm sharing the following code with users:

```
/* Sharing: remove broken icons from the Blog Posts Block */
.wp-block-newspack-blocks-homepage-articles .sharedaddy {
  display: none;
}
```

**Comment by allykmyta** [comment] 2020-11-23 22:23
Reported in 25849358-hc. The workaround above was provided in the meantime.

**Comment by adekbadek** [comment] 2021-04-02 15:15
Can't reproduce - the block does not render any share buttons at all. Perhaps this was fixed in the meantime somewhere else. Feel free to reopen with new reproduction step if this resurfaces.

**Closed by adekbadek** 2021-04-02 15:15 UTC
Labels: bug
