### ISSUE TITLE
"Load more" button loads irrelevant category posts

### ISSUE THREAD

**Issue by kmrpankaj** [Automattic/newspack-blocks#392] opened 2020-03-03 19:00 UTC
**Describe the bug**
Clicking the "load more" button brings irrelevant posts when a category is assigned in the "Display Settings"

**To Reproduce**
1. Create a new post or page.
2. Add a "**Blog Post**" block
3. Add a category from the "**Display Settings**" on the right panel.
4. Enable the **Show "More" Button**
5. Publish the page.

**Screenshots**

**Expected behavior**
When you click on the Load more button, loaded posts should be relevant to the assigned category to that block.

**What happened instead**
When you click on the Load more button it also brings posts from other categories.

The issue was reported here 2757285-ZD

Tested with TwentyTwenty, Hemingway Rewritten themes on WordPress.com Premium plan.

**Comment by kristarella** [comment] 2020-03-09 03:34
Also reported here: https://github.com/Automattic/wp-calypso/issues/39818

**Comment by davipontesblog** [comment] 2020-03-09 12:41
@kristarella mentioned:

19227051-hc

atomic site
maisha theme

@nielslange mentioned:

2762946-zd

**Comment by catkiinson** [comment] 2020-03-09 19:01
19190117-HC

Simple site
Shawburn theme

**Comment by rantoncuadrado** [comment] 2020-03-12 08:20
2777459-zen

Simple site
Site Hever

**Comment by lakellie** [comment] 2020-03-12 18:43
Another user report in #2785514-zen

**Comment by ktyfuller604** [comment] 2020-03-20 19:41
another user report in [#2805123-zen](https://woothemes.zendesk.com/agent/tickets/2805123)

**Comment by rahul020691** [comment] 2020-03-23 17:40
19624685-hc
Simple site
Theme: TwentyTwenty

P.S. Happening with tag filter too, not just category.

**Comment by jeffersonrabb** [comment] 2020-03-23 19:00
Thank you all for reporting this! Here's an update. The fix was made and merged on 3/17 in this PR: https://github.com/Automattic/newspack-blocks/pull/415. However, there's a lag between when a fix lands in `newspack-blocks` and when it gets deployed to WordPress.com. https://github.com/Automattic/newspack-blocks/issues/411 is a duplicate of this issue, and there's discussion of this starting [here](https://github.com/Automattic/newspack-blocks/issues/411#issuecomment-601196951). @noahtallen is going to update the other issue when the fix hits WP.com, so I recommend subscribing to notifications on that one.

**Closed by jeffersonrabb** 2020-03-23 19:00 UTC
Labels: bug

**Comment by noahtallen** [comment] 2020-03-25 21:24
v1.2 of the newspack posts block is now running on all simple and Atomic sites, so the issue should now be resolved in production.
