### ISSUE TITLE
Post Carousel Block: Switching between first and last post Display Blank Image

### ISSUE THREAD

**Issue by edwinho89** [Automattic/newspack-blocks#519] opened 2020-06-11 12:56 UTC
Post Carousel block displays blank images when switching between first and last post on post carousel block.

**To Reproduce**
1. Publish a few posts with featured images
2. Create a new post or page, insert post carousel block
3. Activate Anemone theme
4. Visit the page with post carousel block

Newer themes does not reproduce the issue. The issue appears to be relating with Anemone theme specifically.

**Screenshots**

Sample gif available in ZD #3041533-zen

**Expected behavior**

The post carousel block works as normal on the editor.

![image link 2](https://cldup.com/QrgvERH-Pl.png)
image link: https://cloudup.com/cFi9kxKcGOz

**Comment by adekbadek** [comment] 2021-07-16 16:00
Could not reproduce, but did encounter different issues with Anemone: the slider are overflowing and post titles (and other data) is not displayed:

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/7383192/125975975-f7ece592-8038-41fb-8674-530f21147bb5.png">

The former seems to result from a conflict with Jetpack slider.

**Comment by adekbadek** [comment] 2022-01-07 14:44
Closing. This should probably be resolved in the Anemone theme, since it was not reported for any other themes.

**Closed by adekbadek** 2022-01-07 14:44 UTC
Labels: bug, [Block] Carousel
