### ISSUE TITLE
Blog Posts Block (Homepage Posts): missing the "load more" button?

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/newspack-blocks#629] opened 2020-11-15 12:26 UTC
**Describe the bug**
I could be missing something, but it doesn't seem like the "load more" button is even available for new block instances?

**To Reproduce**
1. On a WordPress.com Simple site, go to My Site > Site > Pages > Add new page
2. Add a fresh Blog Posts block
3. Ensure there are less posts displayed than there are published posts (eg: show only two posts)
4. Check the block settings for the "load more" button option
5. No button option 

**Screenshots**
Firefox 82.0.2: 

![firefox13:20:09](https://user-images.githubusercontent.com/36608681/99184727-552a6300-2745-11eb-96ff-c5d6c03da8d5.png)

Chrome 86.0.4240.198:

![chrome13:21:57](https://user-images.githubusercontent.com/36608681/99184770-991d6800-2745-11eb-9e90-5672f85ad259.png)

**Expected behavior**
It doesn't look like the button is intended to be missing but I haven't noticed it recently and I am pretty sure it hasn't been moved? I usually expect to find it in the Display Settings section, as in this screenshot:
https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/#display-settings

Edited to add: I also tried-

* Switching off infinite scroll
* Reducing the amount of posts per page in both WP Admin > Settings > Reading, and in My Site > Manage > Settings > Writing
* Opening the page from WP Admin, in case Calypso had anything to do with it.

**Comment by laurelfulford** [comment] 2022-05-02 20:22
I can't recreate this issue on a WP.com simple site:

![image](https://user-images.githubusercontent.com/177561/166319421-9e6082a5-a6a0-4228-a410-1b4ed2e3f0f4.png)

... but I wonder if the issue was that this site was private -- right now, the block will display a message instead of the Load More button toggle if your site is private, but it didn't always:

![image](https://user-images.githubusercontent.com/177561/166319270-1a380f03-d41e-4f6d-afd8-c077d815c5ce.png)

The above was fixed in the block in [September 2020](https://github.com/Automattic/newspack-blocks/pull/588), which was before this bug report. But I don't know when this fix was moved to WP.com -- sometimes updates take a while to get synced. 

I'm going to close this issue as 'can't reproduce' as I think this was fixed on WP.com after this issue was reported -- @sophiegyo if I've missed something here or if you're still seeing this issue, please let us know and we can reopen the issue!

**Closed by laurelfulford** 2022-05-02 20:22 UTC
Labels: [Block] Homepage Posts
