### ISSUE TITLE
Article Carousel: Author not appearing in editor

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#370] opened 2020-02-13 22:58 UTC
When using the Article Carousel block, the author and author avatar do not appear in the editor preview:

![image](https://user-images.githubusercontent.com/177561/74486203-48ed3e80-4e71-11ea-9031-531da5b07cad.png)

They do display as expected on the published page, though.

**Comment by jeffersonrabb** [comment] 2020-05-03 19:11
Duplicate of https://github.com/Automattic/newspack-blocks/issues/445

**Closed by jeffersonrabb** 2020-05-03 19:11 UTC
Labels: bug
