### ISSUE TITLE
Blog Posts Block: Custom HTML gets stripped in excerpts

### ISSUE THREAD

**Issue by Robertght** [Automattic/newspack-blocks#1346] opened 2023-01-12 14:01 UTC
**Describe the bug**
Custom HTML items like links will get stripped from manual post excerpts.

**To Reproduce**
1. Publish a post or two and make sure it has a custom excerpt that contains some Custom HTML(I tested with links)
2. Create a new page and add the Blog Posts block.
3. Enable the excerpts and make sure the Custom HTML-related content is visible(adjust the word count)
4. Publish the page and check the results

**Expected behavior**
The text gets outputted correctly, but the custom HTML isn't so instead of  `<a href="link-to-some-page">link</a>` we get just "link"

This was reported in 5859415-zen and as a workaround a user can have the posts on the default post archive of that theme use the [Query Loop Block](https://wordpress.com/en/support/full-site-editing/theme-blocks/query-loop-block/). 

The user claims this was working fine Saturday, but it changed out of nowhere.

Initially reported in Slack: p1673529481724749-slack-C01C378QWRX

**Comment by laurelfulford** [comment] 2023-01-12 16:26
Thanks for reporting this, @Robertght! 

This is (confusingly!) a duplicate of an older issue in this repo (#888). The [change that caused it](https://github.com/Automattic/newspack-blocks/pull/874#issuecomment-929630315) was included in the 1.39.0 block release, and [WP.com was _just_ synced from 1.37.1 to 1.60](https://github.com/Automattic/newspack-blocks/issues/888), which is why it just started happening there.

I'm going to close this issue, but copy your comment over -- please let me know if you have any questions about the above. Thanks!

**Closed** 2023-01-12 16:26 UTC
Labels: [Type] Bug, Block: Blog Posts
