### ISSUE TITLE
Blog Posts Block: Page navigation instead of Load more posts ajax button

### ISSUE THREAD

**Issue by mmprep** [Automattic/newspack-blocks#709] opened 2021-02-26 12:02 UTC
I have blocks that display posts by selecting them from a variety of tags.

```
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"100%"} -->
<div class="wp-block-column" style="flex-basis:100%"><!-- wp:newspack-blocks/homepage-articles {"className":"is-style-default","showDate":false,"moreButton":true,"showAuthor":false,"columns":1,"postsToShow":10,"mediaPosition":"left","tags":["130","3694","861","20","21","765","1537","2673","4224","1482","1532","114","1039","1565","2968","1943","2858","279"],"imageScale":1,"mobileStack":true,"postType":[],"align":"wide"} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

Is it possible to display posts without ajax button Load more posts, but with normal page navigation?

**Comment by laurelfulford** [comment] 2021-03-01 18:37
Thanks for filing this issue, @mmprep! 

It looks like this is a duplicate of #570, so I'm going to close this issue in favour of that one, but if you have any specific details you'd like to add there, please do!

**Closed by laurelfulford** 2021-03-01 18:37 UTC
