### ISSUE TITLE
Post Carousel - arrows break out of carousel when nested in a cover block

### ISSUE THREAD

**Issue by aleone89** [Automattic/newspack-blocks#578] opened 2020-08-23 08:46 UTC
**Describe the bug**
When the post carousel block is nested inside of a cover block, the post carousel arrows break out of the carousel, and are placed at the top of the cover block. 

The arrows also take on some of the styling elements (like colour and background colour of heading and paragraph blocks also in the cover block. 

**To Reproduce**
Steps to reproduce:
1. Go to Pages > Add new > add page title 
2. Add a cover block > make full width
3. Add a post carousel (must have posts in the site) 

**Screenshots**

https://d.pr/i/SanGv9

**Expected behaviour**
The post carousel block to remain complete and together whilst nested in the cover block.

**Comment by laurelfulford** [comment] 2020-09-28 15:59
Thanks for filing this, @aleone89! 

I can't say for certain without viewing the site, but looking at the screenshot this doesn't look like the Post Carousel block that comes with Newspack (it is not the only block with that exact name, so it's easy to mix 'em up!). That block only will display a post if it has a featured image, and only displays the post title, author and date -- no excerpt. 

This is what I get when I mix the Post Carousel block in Newspack with a full-width cover block:

![image](https://user-images.githubusercontent.com/177561/94456873-aae08700-0168-11eb-8990-bcfb64e67e55.png)

It might be that this screenshot is just showing the arrows popping out, and not the full block. But one possible way to verify that it's using the same block could be adding the Post Carousel block from the 'plus' menu in the editor's top-left corner -- that way, you see what each block is categorized under:

![image](https://user-images.githubusercontent.com/177561/94456972-cba8dc80-0168-11eb-9977-effd3769e5b2.png)

Can you verify that you're using the same block? 

Just let me know if you have any questions about this at all -- thanks!

**Comment by laurelfulford** [comment] 2022-05-02 18:46
Unfortunately it looks like the original screenshot no longer loads. I can't recreate this issue using the Cover Block + Post Carousel block, though, so I'm going to close it: 

![image](https://user-images.githubusercontent.com/177561/166306567-c19caec6-3e88-4f67-97f4-7924a58e7236.png)

@aleone89 if you can still reproduce or have any questions at all about this, please let me know and we can definitely reopen and reexamine -- thanks!

**Closed by laurelfulford** 2022-05-02 18:46 UTC
Labels: question
