### ISSUE TITLE
Homepage Block: Add data-hero to images

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-blocks#861] opened 2021-09-07 20:16 UTC
An AMP analysis of a Newspack site returned this recommendation:

> Let AMP Caches and Optimizers optimize your hero images by adding the `data-hero` [attribute](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/?format=websites#hero-image-optimization) to images in your first viewport. This can improve image loading times by up to 50%.

Is that attribute something we can add to the Homepage Posts block's featured images? The supplied documentation suggests it be used in the `<amp-img>` tag.

https://github.com/Automattic/newspack-theme/issues/1502 will address adding this attribute to individual posts' featured images in the Newspack theme.

**Comment by laurelfulford** [comment] 2021-09-08 17:09
It looks like the AMP plugin [should be adding this attribute](https://github.com/ampproject/amp-wp/pull/6435) as of v2.13, and I've tested and confirmed it's being added to the blocks using v2.14. Unfortunately, we have some live sites running an older version of the plugin due to other issues, so this isn't working there yet. 

After discussing with @gamebits, we're going to close this issue and defer to the fix in the plugin instead.

**Closed** 2021-09-13 21:36 UTC
Labels: [Block] Homepage Posts, AMP
