### ISSUE TITLE
Homepage Posts: Related posts option

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-blocks#713] opened 2021-03-08 14:23 UTC
**Is your feature request related to a problem? Please describe.**
Many publishers want to show related posts on their site. They can do so using Jetpack's related posts feature, shown at the bottom of each post, but this provides very few options and only one display location. The display of these posts is then also sometimes inconsistent with the rest of the posts on display.

**Describe the solution you'd like**
When configuring a homepage posts block users will have a "Related posts" option, similar to the "Display specific posts" option that would remove the available filters and instead piggyback on Jetpack's query for grabbing related posts.

**Describe alternatives you've considered**
Making a block in Jetpack that matches the options of the homepage posts block, but that might be unwanted duplication of the block options logic.

**Additional context**
Several publishers have asked for this feature.

**Comment by gamebits** [comment] 2021-09-03 05:23
Jetpack does have a [Related Posts block](https://jetpack.com/support/related-posts/), but it's available in the block editor only when Jetpack's "Show related content after posts" option is enabled. It has numerous options that are not available in the Homepage Posts block — but none of the filtering options available in the Homepage Posts block, like filtering by tag (https://github.com/Automattic/newspack-blocks/pull/297), category (https://github.com/Automattic/newspack-blocks/pull/821), or author (https://github.com/Automattic/newspack-blocks/pull/60).

Our own Related Posts block that uses Jetpack's logic, but applies our own Homepage Block's filtering options, would be a welcome addition.

**Comment by laurelfulford** [comment] 2022-05-02 17:30
Closing this as a duplicate of #1108 (this is an older issue, but that one captures our more up-to-date thinking around this feature).

**Closed by laurelfulford** 2022-05-02 17:30 UTC
Labels: enhancement, feature request
