### ISSUE TITLE
FSE plugin conflict

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-blocks#324] opened 2020-01-08 15:17 UTC
**Describe the bug**

When `Full Site Editing` plugin is installed, `Newspack Blocks` plugin installation fails. 
This is caused by (though possibly not exclusively) by these constants reinitialisation:

https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/blog-posts-block/index.php#L10-L12

The code is there because `wp-calypso` synchronises the `blog-posts-block` from this repo.

**To Reproduce**
1. Install & activate Full Site Editing plugin
2. Try installing & activating Newspack Blocks plugin

**Screenshots**

![image](https://user-images.githubusercontent.com/7383192/71989501-19279700-3232-11ea-9174-f8c7ea6125a1.png)

**Expected behavior**

Newspack Blocks plugin is activated without issues.

**Comment by obenland** [comment] 2020-01-20 16:17
@marekhrabe During Iteration Planning it came up that you might have started a Pr on this already? Is that public yet?

**Comment by obenland** [comment] 2020-01-31 20:45
Fix in https://github.com/Automattic/wp-calypso/pull/39208.

**Comment by adekbadek** [comment] 2020-03-12 11:14
This is still causing issues when calling [activate_plugin](https://developer.wordpress.org/reference/functions/activate_plugin/), which [is called by Newspack plugin](https://github.com/Automattic/newspack-plugin/blob/6a10fb55106053265598fa4495ce715a91562d3a/includes/class-plugin-manager.php#L539). 

The complete error is:

---

<b>Notice</b>:  Constant NEWSPACK_BLOCKS__BLOCKS_DIRECTORY already defined in <b>/srv/htdocs/wp-content/plugins/newspack-blocks/newspack-blocks.php</b> on line <b>15</b><br />
<b>Notice</b>:  Constant NEWSPACK_BLOCKS__PLUGIN_DIR already defined in <b>/srv/htdocs/wp-content/plugins/newspack-blocks/newspack-blocks.php</b> on line <b>16</b><br />
<b>Notice</b>:  Constant NEWSPACK_BLOCKS__VERSION already defined in <b>/srv/htdocs/wp-content/plugins/newspack-blocks/newspack-blocks.php</b> on line <b>17</b><br />
<b>Warning</b>:  require_once(/wordpress/plugins/full-site-editing/0.23/blog-posts-block/class-newspack-blocks.php): failed to open stream: No such file or directory in <b>/srv/htdocs/wp-content/plugins/newspack-blocks/newspack-blocks.php</b> on line <b>19</b><br />
<b>Fatal error</b>:  require_once(): Failed opening required '/wordpress/plugins/full-site-editing/0.23/blog-posts-block/class-newspack-blocks.php' (include_path='/:.') in <b>/srv/htdocs/wp-content/plugins/newspack-blocks/newspack-blocks.php</b> on line <b>19</b><br />

---

To reproduce:
1. Activate FSE plugin
1. Activate Newspack plugin
1. Visit Newspack's configuration wizard - at `/wp-admin/admin.php?page=newspack-setup-wizard#/installation-progress`
1. Observe that Newspack Blocks is not activated:
![image](https://user-images.githubusercontent.com/7383192/76515939-c9946000-645a-11ea-8e32-ab5db56d8fa7.png)

Let me know if I should rather create a new issue for that.

**Comment by obenland** [comment] 2020-04-07 16:44
Tested and was able to reproduce it with https://github.com/Automattic/newspack-plugin.

@adekbadek @jeffersonrabb How common is this scenario or how much of an edge case it?

**Comment by adekbadek** [comment] 2020-04-07 19:40
@obenland It just came up in testing, never in an actual ticket or anything like that. So I'd say right now it's not common at all :)

**Comment by obenland** [comment] 2020-04-07 19:42
Thanks for the update! In that case, how about we keep this closed as it fixed the problem for newspacks-blocks. If at some point in the future it becomes more of a problem for news pack-plugin, let's deal with it then.

**Comment by kriskorn** [comment] 2020-06-08 10:20
A similar issue came up on a WordPress.com Business site, which has custom plugins installed. 

Chat: 18349041-hc 
Slack: p1591609822159900-slack-newspack-a8c

The user downloaded Newspack Blocks from GH and installed the plugin, which promptly brought down their site with below error:

`PHP Fatal error:  Cannot declare class Newspack_Blocks, because the name is already in use in /wordpress/plugins/full-site-editing/1.8/newspack-blocks/synced-newspack-blocks/class-newspack-blocks.php on line 11`

_Opening this as discussed in Slack._

**Comment by obenland** [comment] 2020-06-09 21:25
[The FSE plugin checks for](https://github.com/Automattic/wp-calypso/blob/ea8597e56ffeef19043669bde84211a2f08e1080/apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php#L224) `newspack-block/newspack-blocks.php` when determining whether to load newspack blocks or not. When downloaded from GitHub, the slug is `newspack-block-(HASH|branch-name)/newspack-blocks.php` so we'll need to add a case for that. :(

**Closed** 2020-06-25 09:31 UTC
Labels: [Block] Homepage Posts, bug
