### ISSUE TITLE
Most popular posts block

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-blocks#1204] opened 2022-07-13 15:08 UTC
Most popular posts block can be added in sidebar and can retrieve data from Google Analytics, showing most popular posts within defined time period.

**Comment by adekbadek** [comment] 2022-09-23 08:12
Duplicate of https://github.com/Automattic/newspack-blocks/issues/49

**Closed by adekbadek** 2022-09-23 08:12 UTC
