### ISSUE TITLE
Blog Posts Block: Wrong author link appears

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/newspack-blocks#401] opened 2020-03-10 09:16 UTC
**Describe the bug**
The wrong author link appears in the blog posts block.

**To Reproduce**
* When you click the author link on the home page "blog posts block", the link goes to a 404 error
The link here - https://d.pr/i/K2mT5e
* The link the block creates is - https://joelvsarthritis.co.uk/author/Joel/
rather than 
https://joelvsarthritis.co.uk/author/joelvsarthritis/
* So the link it is generating isn't right
* One example is to look directly at the post 
https://joelvsarthritis.co.uk/an-interview-author-my-dark-guardians/
When viewed directly the author is "joelvsarthritis" but when clicked from the block it is "Joel". 
* Pls note the user has turned off the show author option in the block at the moment so the link won't appear when you first view the page.

**Expected behavior**
The link in the block to provide a link to posts by the correct author.

**Comment by Robertght** [comment] 2020-03-10 19:51
Found another which is caused by the change of the display name in the profile name. #p1583841759045700?thread_ts=1583754711.043100&cid=C02FMH4G8-slack

**Comment by laurelfulford** [comment] 2020-03-11 19:43
I can confirm this is happening on WP.com, but not on self-hosted sites. I wonder if it has to do with the changes in #372?

**Comment by andreabadgley** [comment] 2020-03-14 13:29
Hi there! I just came to check in on this -- it looks like there's a pull request in testing and review. I'll let the user know we're still working on it and we'll update when we have more information.

**Comment by noahtallen** [comment] 2020-03-20 23:24
Hi! The update for v1.1.0 will be released on wpcom simple and Atomic at some point next week. (Not sure which day yet :)) This should include the fix that already exists in Newspack.

**Comment by SiobhyB** [comment] 2020-03-26 16:13
I just received another report of this in 19688499-hc (I'll be following up with the user in 2820912-zen). 

Is the fix still on track to be released this week?

**Closed** 2020-03-26 18:42 UTC
Labels: [Status] Has Pull Request, bug

**Comment by laurelfulford** [comment] 2020-03-26 18:45
> Is the fix still on track to be released this week?

I don't think so -- the fix has just been reviewed and merged, so it will be the block plugin's release next week (usually out by Tuesday at the latest).

@noahtallen I'm not sure how this lines up with when things are synced on WP.com; is it safe to say that the next block plugin release will be synced to WP.com by the end of next week?

**Comment by noahtallen** [comment] 2020-03-26 22:01
We can definitely try to make that happen :) Let me know when the release is ready and I can start the update process!

**Comment by laurelfulford** [comment] 2020-03-27 16:57
Will do - thanks!

**Comment by noahtallen** [comment] 2020-03-31 20:45
Update for wpcom: https://github.com/Automattic/wp-calypso/pull/40629

**Comment by laurelfulford** [comment] 2020-03-31 20:54
Thanks @noahtallen! 🎉

**Comment by andreabadgley** [comment] 2020-04-06 13:48
I followed up with the user from the original report in 2852219-zen.
