### ISSUE TITLE
Reusable Block :: Blog Post Block featured image isn't showing on the editor. 

### ISSUE THREAD

**Issue by mdtanjid0** [Automattic/newspack-blocks#1371] opened 2023-01-26 17:16 UTC
### Quick summary

If we convert a Blog post block to a Reusable block, the featured image breaks in the editor. 

### Steps to reproduce

1. Take a Blog post block.
2. And make sure you have some blog posts with featured images.
3. Convert the Block post block to a Reusable block. 
4. And see the featured image is broken in the editor. 

### What you expected to happen

It should show in the editor as the frontend. 

### What actually happened

It breaks in the editor; the base URL shows undefined: 

<img width="1003" alt="Screen Shot 2023-01-26 at 23 13 22" src="https://user-images.githubusercontent.com/54123436/214908800-f3f5df4e-ddb9-499f-9063-1c359c0c79aa.png">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Sees these errors on the console: 

<img width="1153" alt="Screen Shot 2023-01-26 at 23 15 04" src="https://user-images.githubusercontent.com/54123436/214908897-4445cf69-b288-4bb8-a33e-f3bc4462c3c5.png">

**Comment by laurelfulford** [comment] 2023-02-15 20:57
Thanks for reporting this issue @dpasque and @mdtanjid0! 

This is a duplicate of an existing issue, #973; I'm going to close this and defer to the older issue, but I'll copy over the relevant Zendesk ticket to a new comment there. Just let me know if you have any questions at all about this!

**Closed by laurelfulford** 2023-02-15 20:57 UTC
Labels: User Report, [Type] Bug, [Pri] Normal

**Comment by dpasque** [comment] 2023-02-15 21:07
@laurelfulford Ahh, sorry about the duplicate miss! Thanks for catching and cleaning that! 🙇 Sounds great!

**Comment by laurelfulford** [comment] 2023-02-16 21:12
@dpasque No worries! It's a dense list to go through 😄 I only remembered this one because I helped test it before!
