### ISSUE TITLE
Donate Block Sporadically Not Rendered In Frontend

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-blocks#538] opened 2020-06-26 11:16 UTC
**Describe the bug**
Donate block occasionally renders blank. This has been observed on https://montanafreepress.org/, both on the homepage and in a campaign. I haven't found any reliable way to reproduce, although I've seen it several times.

Possible cause could be a condition where `Newspack\Donations` is not available at the time of block rendering, and rendering is aborted [here](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/donate/view.php#L16-L18). 

**Screenshots**
<img width="1423" alt="Screen Shot 2020-06-24 at 12 07 24 PM" src="https://user-images.githubusercontent.com/1477002/85851554-e7bd6c00-b77c-11ea-8f3c-e9768a2c22f7.png">

![File](https://user-images.githubusercontent.com/1477002/85851534-d96f5000-b77c-11ea-92fa-c82f2621035b.jpg)

**Expected behavior**
Donate block should be visible.

**Comment by adekbadek** [comment] 2022-01-07 14:37
Can't reproduce, closing.

**Closed by adekbadek** 2022-01-07 14:37 UTC
Labels: bug, [Block] Donate
