### ISSUE TITLE
Blog Posts block: gap/height issue affecting several elements

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/newspack-blocks#508] opened 2020-05-15 13:16 UTC
There's a gap/height issue affecting several elements when the Blog Posts block is used on a page.

This has been mentioned a number of times for different elements:

https://github.com/Automattic/themes/issues/1988
https://github.com/Automattic/themes/issues/1803
https://github.com/Automattic/themes/issues/1774
https://github.com/Automattic/themes/issues/1707

But I don't think it's specific to a theme and is actually more widespread to the block and more specifically the `.wpnbha` element. In my case, it's the sharing buttons that were affected.

#### Steps to reproduce

1. Add the theme Aquene
2. Make your site public/hidden
3. Create and publish a couple of posts
3. Add the Blog Posts block to a page
4. Add sharing buttons such as LinkedIn, Facebook, Twitter etc. to your page
5. Notice the gap added by the extra top padding

![Screen Shot 2020-05-15 at 13 47 27](https://user-images.githubusercontent.com/16645645/82053986-85be1100-96be-11ea-8f7f-dabe1166758a.png)

#### What I expected

No height issue, things to be aligned.

#### What happened instead

There's some extra padding pushing things down. I used the following CSS code to fix things:

```
.wpnbha button {
    margin-top: 0;
}
```

**Comment by laurelfulford** [comment] 2020-06-04 16:53
Thanks for reporting this, @cecilearkay! 

Just to close the loop on some of the above issues:

https://github.com/Automattic/themes/issues/1988 has also [been reported in this repo](https://github.com/Automattic/newspack-blocks/issues/482), and a fix has been queued up, it just needs to be synced with WP.com - I've added a comment to the theme issue and closed it.

https://github.com/Automattic/themes/issues/1803 and https://github.com/Automattic/themes/issues/1774 look to be clashes between the theme and the block; theme-specific styles are overriding what the block is doing. The block uses some common classes for different elements (the excerpt, title, post meta and featured image); the original hope was that it would help it pick up the theme styles easier, though in some cases where themes are really pushing those styles, it doesn't play nicely. 

For this issue, my best guess is that the ['Load More' styles](https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/view.scss#L332) are applied to other buttons incorrectly, but I haven't been able to replicate the same set up. It looks like the Share buttons are showing up for the posts in the block in your screenshot, but they only show up at the bottom of the page for me.

When you have a moment, could you share a screenshot of your Sharing settings? So far I've tried enabling them for everything, or specially posts or pages, and adding the block to the front page, a subpage, and a post, but no dice! (I did manage to get Ratings showing up for the posts in the block though ¯\_(ツ)_/¯ )

Also if I've misunderstood the screenshot and the buttons are not appearing in the block, please let me know!

**Comment by cecilearkay** [comment] 2020-06-13 08:49
I'm sorry, I realize I didn't mention you need an AT site. You can see the issue live here on my test site:

https://crkatomicsite.wpcomstaging.com/test-blog-posts-block/

The settings I have are:

* Likes & Sharing activated in each posts
* Likes & Sharing deactivated on that specific page

And in Marketing > Sharing Buttons, I have these:

<img width="1067" alt="Capture d’écran 2020-06-13 à 10 48 50" src="https://user-images.githubusercontent.com/16645645/84564642-800e2680-ad63-11ea-9fda-63b7057ca0af.png">

**Comment by laurelfulford** [comment] 2020-06-15 21:45
Thanks @cecilearkay! 

I can confirm that it is the styles for the load more button getting picked up by the LinkedIn button -- right now it doesn't specify a class, just the block container. 

Updating those styles to use the Load More button class should fix it.

**Closed** 2020-06-30 19:56 UTC
Labels: [Block] Homepage Posts, [Status] Has Pull Request, bug
