### ISSUE TITLE
"Related Posts" block as a variation on Homepage Posts

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-blocks#1108] opened 2022-04-18 15:24 UTC
**Is your feature request related to a problem? Please describe.**
A lot of sites use the Homepage Posts block as a related posts/recirculation module inside a Campaigns prompt. However, this can get cumbersome—e.g. categories/tags need to be manually configured per block instance—and there's a good opportunity to officially support this use case and simplify the editorial process at the same time.

**Describe the solution you'd like**
WP supports [block variations](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/), which lets you register a variation of an existing block but overwrite some or all of its attributes and behavior. Maybe we could create a variation of the Homepage Posts block with more limited query options that are based on the current post? For example, "show posts with the same categories or tags as the current post." This would let sites drop the block into an After Article Content widget area and edit it from one place.

**Describe alternatives you've considered**
An alternative would be an entirely new block with similar display options as the Homepage Posts block, if the variations API doesn't get us everything we need.

**Comment by adekbadek** [comment] 2022-04-19 12:18
Closely related to https://github.com/Automattic/newspack-blocks/issues/873, which describes a change to how the HP block **queries for posts**. This issue here describes simplifying the query options by creating block variations.

**Comment by adekbadek** [comment] 2022-09-23 08:16
Closing as duplicate of https://github.com/Automattic/newspack-blocks/issues/1177

**Closed by adekbadek** 2022-09-23 08:16 UTC
Labels: enhancement
