### ISSUE TITLE
Homepage Posts block: add sort option (ascending publish date)

### ISSUE THREAD

**Issue by tbradsha** [Automattic/newspack-blocks#715] opened 2021-03-08 21:58 UTC
**Is your feature request related to a problem? Please describe.**
Currently there doesn't appear to be a way to show posts in ascending publish date. This is useful for people who have podcasts, books, or anything where it's important to start at the beginning.

**Describe the solution you'd like**
Add a Sort setting to choose descending or ascending publish date order.

**Describe alternatives you've considered**
There are a few options listed here:
https://wordpress.com/support/show-your-posts-in-chronological-order/

But none are as robust or elegant as this block could be.

**Comment by laurelfulford** [comment] 2022-05-02 20:32
Closing as a duplicate of #509.

**Closed by laurelfulford** 2022-05-02 20:32 UTC
Labels: enhancement, feature request, Involves Happiness
