### ISSUE TITLE
Post Carousel - Clicking right arrow moves to the left instead of right

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/newspack-blocks#555] opened 2020-07-25 12:50 UTC
**Describe the bug**
This happens on a site using the Dyad 2 theme, and it's not easy to reproduce. It happens every once in a while so we haven't been able to draw a pattern here yet on why this is happening.

1) Post carousel sometimes slides left when clicking the right arrow

Reported on #3161327-zen

**Comment by adekbadek** [comment] 2022-01-07 15:09
Closing due to irreproducibility and issue being localised to a single theme.

**Closed by adekbadek** 2022-01-07 15:09 UTC
Labels: bug, [Block] Carousel
