### ISSUE TITLE
Featured images not displayed on the published page in the Blog Posts block

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/newspack-blocks#718] opened 2021-03-13 20:51 UTC
#### Steps to reproduce

1. Add the Blog Posts block
2. Select a category
3. Select the option to "Show featured image"
3. Featured image displayed in the Editor
4. Publish post
5. Featured images not displayed in the Frontend, only post titles.

#### What I expected
Links to posts with featured images.

#### Screenshot / Video

<img width="1457" alt="Screenshot on 2021-03-13 at 21-45-44" src="https://user-images.githubusercontent.com/9025643/111044009-44b19d00-8446-11eb-81a3-dd72e058d83c.png">
<img width="828" alt="Screenshot on 2021-03-13 at 21-46-07" src="https://user-images.githubusercontent.com/9025643/111044013-48ddba80-8446-11eb-9919-9d4bc159b3f5.png">

**Comment by laurelfulford** [comment] 2021-06-21 15:37
Hi @maciejpilarski! Just to confirm, does this only happen when the featured images are hidden on pages using Jetpack's Content Options? If yes, I'm going to close this to defer to #399, but I just want to make sure I'm not missing something before doing that -- thanks!

**Comment by laurelfulford** [comment] 2022-05-02 17:33
Following up; best I can tell this is a duplicate of #399 so I'm going to close in favour of that issue. 

If I have that wrong, please reopen -- thanks!

**Closed by laurelfulford** 2022-05-02 17:33 UTC
Labels: question
