### ISSUE TITLE
Homepage Posts Block: Featured images conflict with Content Options

### ISSUE THREAD

**Issue by selectedselections** [Automattic/newspack-blocks#399] opened 2020-01-12 21:39 UTC
A user reported that the featured images added to a blog post block, within a blog post, are not displayed unless the theme option **My Site -> Design -> Customize -> Content Options -> Featured Images -> Display on single posts** is enabled [screenshot](https://d.pr/i/sKvIEX)

#### Steps to reproduce
1. Start with a site that includes at least one blog post with a featured image
2. Create a new blog post and add a blog post block to the post 
3. Enable the post block to display featured images
4. When the post is published, the featured images will not appear unless the setting to display featured images on single posts is enabled 

#### What I expected

The blog posts block settings should be independent from the theme settings

#### What happened instead

The content options settings override the blog posts block settings

#### Context / Source

#userreport 

This has been tested across several themes that include the Content Options settings in the Customize tool including Twenty Seventeen, Twenty Sixteen, and Shoreditch 

The issue doesnt persist to an install of the core version of Twenty Sixteen and seems to be .com only.

**Comment by damiannep** [comment] 2020-03-11 10:19
Same issue is the block is used on a page. Then the featured image has to be enabled for pages.

![screenshot](https://user-images.githubusercontent.com/25575134/75635812-13718080-5be7-11ea-807d-280f525299b3.png+)

**Comment by laurelfulford** [comment] 2020-03-11 19:19
I can recreate this. It looks like Content Options prevent the image from loading in the block altogether, rather than simply hiding it.

**Comment by laurelfulford** [comment] 2020-03-12 19:41
@thomasguillot I'd be interested in your thoughts on this one! 

It seems to work, but I'm wonder if would be wise to remove the the `jetpack_featured_images_remove_post_thumbnail` filter on `get_post_metadata` before the block output begins, or if that will cause other obvious issues that I'm not thinking of (very likely!).

**Comment by thomasguillot** [comment] 2020-03-13 12:19
@laurelfulford It's a tricky one...
I see 2 options:
1. We remove `jetpack_featured_images_remove_post_thumbnail` filter when pages/posts are using our homepage posts or carousel block.
2. Directly in Jetpack, we exclude pages/posts that are using our homepage posts or carousel block.
Quite frankly I have no idea how we can achieve either options 😅

**Comment by laurelfulford** [comment] 2020-03-13 17:44
> Quite frankly I have no idea how we can achieve either options

Aw, dangit! 😄 Thanks for looking!

In my testing, I noticed adding the `remove_filter()` before the post output in the block's PHP would keep the featured image hidden for the page itself, but have it displaying for the posts.

The issue I can see is if there's a setup we wouldn't see on Newspack, but could happen on WP.com -- like a blog posts page where the featured image is hidden, and the blog posts page displays the full content -- as soon as the block was used in one of the posts, it would 'unset' the hide featured image setting for posts to come. We'd basically need a way to re-add it afterwards somehow. 🤔

**Comment by ccwalburn** [comment] 2020-05-14 19:56
I found that setting the Content Options only fixes it when the **Show Media on Top** setting is used. If the setting shows the media on the left or the right, the featured image still won't display.

This is from my test site:

![screenshot](https://d.pr/i/eFbbgQ+)
Image URL: https://d.pr/i/eFbbgQ

**Comment by laurelfulford** [comment] 2020-05-14 21:03
Hey @ccwalburn! I don't think that's the same issue -- when that Content Options featured image setting is affecting the block, it fully strips out the featured image, so it wouldn't be showing in the inspector like that (which is unfortunate, because otherwise it would be an easier CSS fix!).

Can you please provide some more information about your test site setup? And does this persist when you switch themes?

**Comment by ccwalburn** [comment] 2020-05-15 12:02
Hi @laurelfulford Thanks for responding! I wasn't sure if this was the right place to add this report or not.

The error was occurring in Intergalactic 2. I only compared it to one of our newer themes, Twenty Twenty, and it did not occur there. 

I just compared it to the themes mentioned in this bug report:  Twenty Seventeen, Twenty Sixteen, and Shoreditch. The error doesn't occur in those, so maybe this bug is specific to Intergalactic 2?

**Comment by laurelfulford** [comment] 2020-05-21 21:33
> The error doesn't occur in those, so maybe this bug is specific to Intergalactic 2?

Looking at it a bit closer, it looks like it has to do with the widths set on the `.entry-title` in the theme -- they're getting picked up by the block, too, and for the lack of a better way to explain it, they're squishing the featured image to be 0px wide. 

It can be fixed by some Custom CSS, if this is on a user site and they have it; otherwise, the styles for the theme would need to be changed. The block uses some common theme classes so it will pick up styles automatically for things like titles and bylines, but this of course can backfire from time to time 😕

**Comment by ccwalburn** [comment] 2020-05-22 22:15
>It can be fixed by some Custom CSS, if this is on a user site and they have it

I played around with some CSS to see if I could fix it but couldn't get it exactly right and since this user has already changed the page to use the Recent Posts block, I think that's OK. (However, if you already have a working fix, I'd still be interested)

>otherwise, the styles for the theme would need to be changed. 

Should I report this as a theme bug for Intergalactic 2 then?

**Comment by AtrumGeost** [comment] 2020-09-03 16:50
This was a bit confusing. I got a user with this problem here 23837628-hc

**Comment by kristarella** [comment] 2020-11-11 03:30
Had another one: 13922642-hc

In this case they had
- Lodestar theme
- featured images on single posts turned off
- added a post carousel to a test post, and the post carousel was empty.

**Comment by eduardozulian** [comment] 2020-12-06 16:14
Another case in 3547659-hc using Twenty Twenty

* This user has the blog posts block in their static home page, where they want to see featured images
* They don't want featured images on internal pages

If you uncheck "Display on Pages" under Content Options, then all the featured images inside the blog posts block are removed.

**Comment by jartes** [comment] 2021-01-07 14:44
Another report on 26842740-hc

**Comment by NoHopeRadio** [comment] 2021-03-17 21:00
Another report from 3817739-zd. 

- Twenty Sixteen theme
- Featured images on single posts turned off
- Was working previously?

**Comment by sajmes** [comment] 2021-08-05 20:58
Another report 30987934-hc

Theme: Ovation
Content options:
- featured images on single posts: on
- featured images on pages: off

Enabling featured images on pages causes featured images to display in blog posts block on published pages.

**Comment by formosattic** [comment] 2021-08-07 08:52
+1 4204734-zd-woothemes

Enabling `Display on pages`  allowed the featured image to display.

**Comment by maciejpilarski** [comment] 2021-08-30 19:28
The problem seems to be also related to the Newspack Post Carousel block, I was able to reproduce the issue on 4258668-zd using the Intergalactic 2 theme.

Enabling Display on pages allowed the featured image to display in the post carousel.

**Comment by marutim** [comment] 2021-11-08 05:17
Another report of the conflict here: 32618019-hc

Enabling "Display on pages" allowed the featured image to display on the blog posts block but then it also displays the featured images on the pages that the user did not want.

**Comment by isocialtish** [comment] 2021-11-08 06:43
This came up in #32352083-hc using the Shoreditch theme.

**Comment by Thelmachido** [comment] 2021-11-17 11:49
Same issue here as well., using the Button 2 theme 

User report: [32650586-hc]
Follow-up ticket: [4459289-zen]

**Comment by sajmes** [comment] 2022-01-14 14:49
Baskerville 2

33656156-hc

**Comment by filipanoscampos** [comment] 2022-05-12 10:33
Another case here, with the Rebalance theme: 5204712-zd-woothemes

**Comment by christianguerrag** [comment] 2023-02-02 21:40
I have a case here 5896604-zen with Apostrophe 2

**Closed** 2024-01-10 16:00 UTC
Labels: bug, [Block] Homepage Posts, [Pri] Normal
