### ISSUE TITLE
Blog Posts Block - Continue Reading Button with Excerpt

### ISSUE THREAD

**Issue by sdixon194** [Automattic/newspack-blocks#480] opened 2020-05-15 20:07 UTC
**Is your feature request related to a problem? Please describe.**

Currently, the "Continue reading" button only appears when there is a certain amount of text in the post. If there's less than a certain character limit, or if you're using an excerpt, the "Continue Reading" link doesn't appear.

**When there's no excerpt**

![Screen Shot on 2020-05-15 at 16:05:54](https://user-images.githubusercontent.com/33553323/82091792-ffa5c880-96c5-11ea-8c1a-627e2debdeb7.png)

**When There's an Excerpt**

![Screen Shot 2020-05-15 at 16 07 00](https://user-images.githubusercontent.com/33553323/82091858-249a3b80-96c6-11ea-909d-5c9725f58ab9.png)

**Describe the solution you'd like**

It would be nice to have a toggle to allow people to turn on or off the continue reading button per their preference. Some people feel it's unclear that you have to click on the post title to be taken to the full post. 

**Additional context**

This was noticed because currently when someone has the blocks in the post set as a group, the blog posts block doesn't pull any preview information at all unless an excerpt is added. 

![Screen Shot on 2020-05-15 at 16:05:16](https://user-images.githubusercontent.com/33553323/82091877-2d8b0d00-96c6-11ea-9f44-5b3118b7c405.png)

**Comment by laurelfulford** [comment] 2020-05-15 20:34
Hey @sdixon194! The block uses WordPress's default excerpt end, `[...]`. That only appears when the excerpt is made up of truncated text from the post body -- if you use a custom excerpt, it's assumed that it ends with a complete stop and won't need the ellipsis.

Some themes will hijack the `[...]` with a filter, and customize it -- usually into a "Continue Reading" or "Read More" link. [Here's an example of the Textbook theme doing it](https://github.com/Automattic/themes/blob/b6ae2c8a45c2317cef960b8c0ef94da55427ffa5/textbook/inc/template-tags.php#L184-L201). I'm not sure what theme you're using in the screenshots, but it looks like it's doing the same thing. 

The filter can only swap in 'Continue Reading' when the `[...]` is present, and it's only present in certain cases. Unfortunately, it's not something we can fix in the block, as it's just using default `the_excerpt()` behaviour - the theme will have the same issue if it uses `the_excerpt()` elsewhere, like in the archives or search results page. 

> This was noticed because currently when someone has the blocks in the post set as a group, the blog posts block doesn't pull any preview information at all unless an excerpt is added.

I'm a little unsure about what this bit means -- is it not pulling an excerpt dynamically under certain circumstances, and you have to set a custom one? Any more details you can provide -- like specific steps used to set up the blocks and see this issue -- would be appreciated!

**Comment by sdixon194** [comment] 2020-05-18 16:10
Hey @laurelfulford ! 

>The filter can only swap in 'Continue Reading' when the [...] is present, and it's only present in certain cases.

Ah this is good to know, thank you! 

> is it not pulling an excerpt dynamically under certain circumstances, and you have to set a custom one?

Yup! So anytime the post in question only contains group blocks, no preview is generated. It seems to ignore it entirely, it just skips over the content in the group block.

- create a new post
- group a bunch of blocks together
- See that the blog posts block skips any grouped content when generating the excerpt

Like in this gif:

![Screen Capture on 2020-05-18 at 12-02-01](https://user-images.githubusercontent.com/33553323/82234479-7aa5f380-98ff-11ea-9127-cd27447a4c8e.gif)

You can see how everything but the last paragraph block is ignored by the blog posts block. In this user's case, they had grouped their entire post so they could apply a single background color to all of the content. 

Let me know if that helps!

**Comment by laurelfulford** [comment] 2020-05-18 18:45
Thanks @sdixon194, that does help!

This looks like a `the_excerpt()` thing, not unique to the block -- I can recreate the issue both with the block, and when searching for the post that's mostly group block, in a theme that uses `the_excerpt()` for the search results. 

It looks like it's by design: https://github.com/WordPress/gutenberg/issues/7268

... but I'm pretty sure that issue predates the Group block, so I'm not sure if how it works now still makes sense in all cases. I created a new enhancement request here, to see if it's possible to keep the "allowed" blocks in the excerpt, even if they're wrapped in a block that should be stripped, like the Group block: https://github.com/WordPress/gutenberg/issues/22431

I'm going to close this since the problem is related to how `the_excerpt()` behaves, but please let me know if you have any questions at all about the above!

**Closed by laurelfulford** 2020-05-18 18:45 UTC
Labels: enhancement

**Comment by laurelfulford** [comment] 2020-05-18 20:23
My Gutenberg issue turned out to be a dupe -- to close the loop, there is a Core issue to address this here: https://core.trac.wordpress.org/ticket/47637
